---

 - name: Set MySQL root password before installing
   debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password | quote}}' vtype='password'

 - name: Confirm MySQL root password before installing
   debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password | quote}}' vtype='password'

 - name: Install the MySQL packages
   apt: name={{ item }} state=installed update_cache=yes
   with_items:
     - mysql-server-5.6
     - mysql-client-5.6
     - python-mysqldb
     - libmysqlclient-dev

 - name: Update MySQL root password for all root accounts
   mysql_user: name=root host={{ item }} password={{ mysql_root_password }} state=present login_user=root login_password="{{mysql_root_password}}"
   with_items:
     - "{{ ansible_hostname }}"
     - localhost
     - root


 - name: Ensure Anonymous user(s) are not in the database
   mysql_user: name='' host={{ item }} state=absent login_user=root login_password="{{mysql_root_password}}"
   with_items:
     - root
     - localhost

 - name: Remove the test database
   mysql_db: name=test state=absent login_user=root login_password="{{mysql_root_password}}"
   notify:
     - Restart MySQL
 - name: Copy the root credentials as my.cnf file
   template: src=my.cnf.j2 dest=/root/.my.cnf mode=0600
